# Generated by Django 4.0.1 on 2022-05-24 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('admit', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('site', models.URLField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
