# Generated by Django 4.0.1 on 2022-05-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
