# Generated by Django 4.0.1 on 2022-05-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closets', '0003_alter_closet_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
